spring.application.name=cart-service

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.streams.application-id=cart-service-group
spring.kafka.streams.bootstrap-servers=localhost:9092

spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde

spring.kafka.streams.state-dir=./data/kafka-streams

spring.kafka.streams.properties.commit.interval.ms=100
spring.kafka.streams.properties.cache.max.bytes.buffering=0

spring.kafka.consumer.auto-offset-reset=earliest