spring.application.name=cart-service

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.streams.application-id=cart-service-group-v2
spring.kafka.streams.bootstrap-servers=localhost:9092
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.state-dir=./data/kafka-streams
spring.kafka.streams.properties.commit.interval.ms=100
spring.kafka.streams.properties.cache.max.bytes.buffering=0
spring.kafka.consumer.auto-offset-reset=earliest

spring.data.redis.host=localhost
spring.data.redis.port=6379
